Disable testing to fix build error
ros-noetic-arch/ros-noetic-pcl-ros pull request #1
Opened 2020-10-09 15:59 UTC by alexdewar

At present https://download.ros.org seems to be down which is causing build failures for this package as testing data cannot be downloaded. Fix by disabling testing, as we don't need it anyway.

2020-10-09 17:47 UTC, acxz requested changes
Could you update the pkgrel and the .SRCINFO file as well so that it syncs properly to the AUR?

While I'm all for disabling testing in packages, I do want to keep the uniformity of the build process for all the packages. Is there a proper solution that can resolve this while still keeping testing on?

Also I can't seem to reproduce the error. [download.ros.org](http://download.ros.org) is live for me.
```
Scanning dependencies of target table_scene_lms400.pcd
Downloading http://download.ros.org/data/pcl/table_scene_lms400.pcd to /home/acxz/.cache/yay/ros-noetic-pcl-ros/src/build/devel/share/pcl_ros/samples/data/table_scene_lms400.pcd... done.
Checking md5sum on /home/acxz/.cache/yay/ros-noetic-pcl-ros/src/build/devel/share/pcl_ros/samples/data/table_scene_lms400.pcd
```

Maybe it was down momentarily?

2020-10-09 18:45 UTC, alexdewar commented
> Could you update the pkgrel and the .SRCINFO file as well so that it syncs properly to the AUR?
Sure.

> 
> While I'm all for disabling testing in packages, I do want to keep the uniformity of the build process for all the packages. Is there a proper solution that can resolve this while still keeping testing on?
> 
> Also I can't seem to reproduce the error. [download.ros.org](http://download.ros.org) is live for me.
When I go there I get a message about renewing the domain name. What do you see? Is it maybe that some CDN mirror is down....?

A proper fix would be to find a mirror for the file, I suppose. I've found random Github repositories which have a file by the same name, but the MD5 hash doesn't match.

> 
> ```
> Scanning dependencies of target table_scene_lms400.pcd
> Downloading http://download.ros.org/data/pcl/table_scene_lms400.pcd to /home/acxz/.cache/yay/ros-noetic-pcl-ros/src/build/devel/share/pcl_ros/samples/data/table_scene_lms400.pcd... done.
> Checking md5sum on /home/acxz/.cache/yay/ros-noetic-pcl-ros/src/build/devel/share/pcl_ros/samples/data/table_scene_lms400.pcd
> ```
> 
> Maybe it was down momentarily?

It fails for me because it downloads an error page instead of the file :cry:

2020-10-09 23:12 UTC, acxz commented
> When I go there I get a message about renewing the domain name. What do you see? Is it maybe that some CDN mirror is down....?

This is what I see: 
![2020-10-09-185647_695x500_scrot](https://user-images.githubusercontent.com/17132214/95638010-55a64e80-0a61-11eb-9489-a33dcdd3b7dc.png)

> A proper fix would be to find a mirror for the file, I suppose. I've found random Github repositories which have a file by the same name, but the MD5 hash doesn't match.

Here is the downloaded file if you want to check the hash yourself:
[table_scene_lms400.txt](https://github.com/ros-noetic-arch/ros-noetic-pcl-ros/files/5357974/table_scene_lms400.txt)

*Had to rename as txt file since GH doesn't support any file format, make sure to rename it.

I think since this a problem, I'll merge the PR in once you add the pkgrel and .SRCINFO changes as well as making an issue upstream so that this can be tracked somehow. I'll make an issue in this repo (or you can do so) that links to the upstream issue and add a patched label to it just so that we are aware. Basically the same protocol for any patched issue under the ros arch packages.

2020-10-10 08:22 UTC, alexdewar commented
It looks like the site is back up again, so I don't think we need this any more. Thanks for your responsiveness though :smile:

2020-10-10 13:31 UTC, acxz commented
Well glad the site is back up, but it is a bit disconcerting. I guess I'll close the PR for now, and if more users report about it, we can think about it then.

2020-10-10 13:31 UTC, closed without merging